# Generated by Django 5.2.8 on 2025-11-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoservice',
            name='ban_image',
            field=models.ImageField(blank=True, null=True, upload_to='furniture/'),
        ),
        migrations.AddField(
            model_name='constructionmaterial',
            name='ban_image',
            field=models.ImageField(blank=True, null=True, upload_to='furniture/'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='ban_image',
            field=models.ImageField(blank=True, null=True, upload_to='furniture/'),
        ),
    ]
