# Generated by Django 5.2.8 on 2025-11-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_cargoservice_ban_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoservice',
            name='ban_image',
            field=models.ImageField(blank=True, null=True, upload_to='cargo/'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='ban_image',
            field=models.ImageField(blank=True, null=True, upload_to='construction/'),
        ),
    ]
