# Generated by Django 5.2.8 on 2025-11-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_service_url_alter_bannerimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='url',
            new_name='urls',
        ),
    ]
