# Generated by Django 5.2.8 on 2025-11-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_url_service_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='urls',
            new_name='link',
        ),
    ]
