# Generated by Django 5.2.8 on 2025-11-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_urls_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bid_des',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
